- Jenkinsfile_nightly
- build.gradle
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/TestType.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/RootControllerTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/entities/TestTypeTest.java
https://tools.hmcts.net/jira/browse/RWA-95
Setup mutation tests.
Added dummy tests.
```
[ ] Yes
[ x] No
```
> RWA-95: Setup mutation Tests

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/WelcomeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/SwaggerPublisherTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/RootController.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/RootControllerTest.java
Re-enables pmd failures changed source set to only scan src/main and cleanup
```
[ ] Yes
[x ] No
```
> Pmd: Cleanup and Re-enable

- build.gradle
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/SwaggerConfiguration.java
- src/main/resources/application.yaml
not camel case for variables in request body.
> Setup swagger-ui page and set api to use snake case

- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/GetWelcomeTest.java
- src/integrationTest/resources/application-integration.yaml
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/advice/CallbackControllerAdvice.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/advice/ErrorLogger.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/RootControllerTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/advice/CallbackControllerAdviceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/advice/ErrorLoggerTest.java
https://tools.hmcts.net/jira/browse/RWA-117
Added controller advice for exceptions.
Added env variable to control whether to also log the exception to the console.
```
[ ] Yes
[ x] No
```
> RWA-117: Added controller advice for exceptions.

- build.gradle
Bump spring boot version OWASP issue with lower version
> Bump spring boot version

- charts/wa-task-configuration-api/Chart.yaml
- charts/wa-task-configuration-api/values.yaml
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yaml
Removing test secret as it was removed from the vault and preventing the app from starting in environments
> Removing test secret 

- Jenkinsfile_nightly
- config/owasp/suppressions.xml
- fix false positive vulnerability
- fix nightly jenkins config
- clean up nightly jenkins config
> Nightly dev

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/ccd/CcdDataServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-192
Add test coverage for CcdDataService
```
[ X] No
```
> Increase test coverage for thirdparty package

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/ccd/CcdDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/idam/IdamSystemTokenGeneratorTest.java
https://tools.hmcts.net/jira/browse/RWA-189
Added IdamSystemTokenGenerator Test to increase mutation test threshold
```
[ ] Yes
[ x] No
```
> Add IdamSystemTokenGenerator Test

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-197
Upgrade azurerm to v2
```
[ ] Yes
[ x] No
```
> RWA-197: Upgrade azurerm version to v2

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-233
Fix terraform to pull s2s secret from s2s vault and copy into wa-vault
```
[ ] Yes
[x ] No
```
> RWA-233: Fix terraform to pull s2s secret from s2s vault and copy into wa-vault

- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/RoleAssignmentClientTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/ConfigurationControllerTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/roleassignment/RoleAssignmentTest.java
- src/integrationTest/resources/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/roleAssignmentsResponse.json
- src/integrationTest/resources/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/roleassignment/roleAssignment.json
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/AutoAssignTaskToCaseworker.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/roleassignment/RoleAssignmentResource.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/roleassignment/RoleAssignmentClient.java
- src/smokeTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/SmokeTest.java
https://tools.hmcts.net/jira/browse/RWA-236
Fix broken smoke test due to port configuration change
Fix role-assignment response
```
[ ] Yes
[X ] No
```
> Update port and  Fix smoke test and role-assignment response

- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/ConfigurationControllerTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/MapCaseDetailsService.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/PermissionsService.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/camunda/CamundaClient.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/MapCaseDetailsServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/PermissionsServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-221
RWA-221: Renaming camunda artefacts to match LLD
```
[ x] Yes
[ ] No
```
> RWA-221: Renaming camunda artefacts to match LLD

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/BaseFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/ConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/RoleAssignmentHelper.java
- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/ConfigurationControllerTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/ConfigureTaskService.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/AutoAssignTaskToCaseworker.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/MapCaseDetailsService.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdmapping/variableextractors/PermissionsService.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/ServiceTokenGeneratorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/thirdparty/ccd/CcdDataService.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-206
Clean up s2s configuration
```
[ ] Yes
[ x] No
```
> RWA-206: Clean up s2s configuration

- README.md
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/BaseFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/ConfigureTaskTest.java
https://tools.hmcts.net/jira/browse/RWA-219
```
[ ] Yes
[x] No
```
> Added task cleanup. Updated README

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/camunda/CamundaTimeTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/configurators/AutoAssignTaskToCaseworkerTest.java
https://tools.hmcts.net/jira/browse/RWA-292
> RWA-292 add junit test for the CamundaTime

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/camunda/CamundaTaskTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/ccd/CaseDetailsTest.java
> RWA-292  Task/fix sonar quality gate

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-292
> RWA-292 fix CVE-2020-28052

- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostTaskConfigurationTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/idam/entities/UserInfo.java
N/A
Added Ignore json properties to UserInfo class to support sidam simulator
```
[ ] Yes
[ x] No
```
> Sidam-simulator update 

- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/idam/IdamServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/auth/role/RoleAssignmentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationControllerTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/CamundaServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/ConfigureTaskServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/DmnEvaluationServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-324
Increase test coverage for task-configuration-api
```
[ ] Yes
[ X] No
```
> Increase test coverage for task-configuration-api

- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostTaskConfigurationTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationController.java
> Added debug logs and waits

- charts/wa-task-configuration-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-356
Bumping java chart version
```
[ ] Yes
[x ] No
```
> bumping java chart version

- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/PostTaskConfigurationTest.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootFunctionalBaseTest.java
> added polling for task retrieval

- build.gradle
Fix CVE-2021-25122
```
[ ] Yes
[ ] No
```
> Fix tomcat cve

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootContractBaseTest.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/consumer/idam/IdamConsumerTestForPostToken.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/clients/IdamServiceApi.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/FeignConfiguration.java
Idam pact test fix
```
[ ] Yes
[ x ] No
```
> Idam pact tests fix

- charts/wa-task-configuration-api/Chart.yaml
- charts/wa-task-configuration-api/values.yaml
https://tools.hmcts.net/jira/browse/RWA-475
Add launch darkly sdk key from vault
```
[ ] Yes
[ x] No
```
> RWA-475: add secret to values.yaml

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/LaunchDarklyFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/SwaggerTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostTaskConfigurationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/utils/CreateTaskMessageBuilder.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationController.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-486
Update swagger to v3 added require s2s headers configuration and functional test to avoid potential issues when updating via dependabot.
```
[ ] Yes
[ x] No
```
> RWA-486: Update Swagger

- audit.json
Fix security test false positive
```
[ ] Yes
[ x] No
```
> Fix security test false positive

- charts/wa-task-configuration-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-496
Bump hmctspublic java chart version
```
[ ] Yes
[ x] No
```
> Bump hmctspublic java chart version

- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/clients/CamundaServiceApi.java
fix variables being updated with incorrect scope when using manual configuration endpoint 
```
[ ] Yes
[x ] No
```
> fix variables being updated with incorrect scope

- build.gradle
Fix CVE-2021-22112
```
[ ] Yes
[ x] No
```
> Fix CVE-2021-22112

- src/functionalTest/resources/application-functional.yaml
- src/main/resources/case_data.json
- src/testUtils/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-522
```
[ ] Yes
[ x] No
```
> Added mandatory noc property to case data

- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationController.java
https://tools.hmcts.net/jira/browse/RWA-526
> format and reuse code

- src/functionalTest/resources/application-functional.yaml
- src/main/resources/case_data.json
- src/testUtils/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-540
> apply fix for the  for document store

- audit.json
> ignoring cross scripting endpoints

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-518
> add task-monitor to the s2s authorised config

- Jenkinsfile_nightly
- security.sh
https://tools.hmcts.net/jira/browse/RWA-649
Fix nightly build failure
```
[ ] Yes
[ X] No
```
> Fix nightly builds failure

- build.gradle
> CVE 2021 27568 fix

- src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/consumer/roleassignment/RoleAssignmentQueryConsumerTest.java
Update state on pact contact test as requested
```
[ ] Yes
[x ] No
```
> Update state on PACT

- build.gradle
- src/main/resources/application-local.yaml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-640
> https://tools.hmcts.net/jira/browse/RWA-640

- build.gradle
> Nightly fx

- README.md
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostConfigureTaskTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/PostTaskConfigurationTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/domain/entities/camunda/enums/CamundaVariableDefinition.java
- src/main/resources/case_data_with_case_management_category.json
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/CamundaServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/CaseConfigurationProviderServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/DmnEvaluationServiceTest.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskconfigurationapi/SpringBootFunctionalBaseTest.java
[RWA-585](https://tools.hmcts.net/jira/browse/RWA-585)
```
[ ] Yes
[X ] No
```
> RWA-585 Update task configuration to include case management category

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-626
```
[ ] Yes
[x ] No
```
> Added FT to nightly build pipeline

- Jenkinsfile_nightly
- charts/wa-task-configuration-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-679
```
[ ] Yes
[x ] No
```
> Upgraded Helm release version

- src/integrationTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/controllers/TaskConfigurationControllerTest.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/clients/CamundaServiceApi.java
- src/main/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/DmnEvaluationService.java
- src/test/java/uk/gov/hmcts/reform/wataskconfigurationapi/services/DmnEvaluationServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-691
> extend endpoint to cope with both wa and ia jurisdictions

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
[RWA-712](https://tools.hmcts.net/jira/browse/RWA-712)
[RWA-712](https://tools.hmcts.net/jira/browse/RWA-712)
```
[ ] Yes
[x ] No
```
> RWA-712 Integrate with Fortify

- charts/wa-task-configuration-api/Chart.yaml
Up the java chart version
```
[ ] Yes
[ ] No
```
> Refactor:Up the java chart version
